id: I32072B6D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:51:49+00:00'
last_modified: '2022-06-08T03:05:52.341182+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01515
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༥ ༼༡༤༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    9B9B:
      image_group_id: I5815
      title: ''
      total_pages: 321
      order: 1
      base_file: 9B9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
