id: P005439
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:50:34.807239
source_metadata:
  id: bdr:W00KG01515
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༥ ༼༡༤༽
  author: ''
  volumes:
    eb634c9d5bea4535bea860d9d461a1db:
      image_group_id: I5815
      title: ''
      volume_number: 1
      total_pages: 321
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
